const LOADING_RESOURCES = 'LOADING_RESOURCES';
const GET_RESOURCES = 'GET_RESOURCES';
const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
const GET_RESOURCES_FAILURE = 'GET_RESOURCES_FAILURE';

const POSTING_RESOURCE = 'POST_RESOURCE';
const POST_RESOURCE = 'POST_RESOURCE';
const POST_RESOURCE_SUCCESS = 'POST_RESOURCE_SUCCESS';
const POST_RESOURCE_FAILURE = 'POST_RESOURCE_FAILURE';

const DELETING_RESOURCE = 'DELETE_RESOURCE';
const DELETE_RESOURCE = 'DELETE_RESOURCE';
const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCES_SUCCESS';
const DELETE_RESOURCE_FAILURE = 'DELETE_RESOURCES_FAILURE';

const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
const SET_PAGINATION = 'SET_PAGINATION';

export {
    LOADING_RESOURCES,
    GET_RESOURCES,
    GET_RESOURCES_SUCCESS,
    GET_RESOURCES_FAILURE,

    POSTING_RESOURCE,
    POST_RESOURCE,
    POST_RESOURCE_SUCCESS,
    POST_RESOURCE_FAILURE,

    DELETING_RESOURCE,
    DELETE_RESOURCE,
    DELETE_RESOURCE_SUCCESS,
    DELETE_RESOURCE_FAILURE,

    SET_SEARCH_TERM,
    SET_PAGINATION
}