const GET_RESOURCES = 'GET_RESOURCES';
const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
const GET_RESOURCES_FAILURE = 'GET_RESOURCES_FAILURE';

const POST_RESOURCE = 'POST_RESOURCE';
const POST_RESOURCE_SUCCESS = 'POST_RESOURCE_SUCCESS';
const POST_RESOURCE_FAILURE = 'POST_RESOURCE_FAILURE';

const DELETE_RESOURCE = 'DELETE_RESOURCE';
const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCES_SUCCESS';
const DELETE_RESOURCE_FAILURE = 'DELETE_RESOURCES_FAILURE';

const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export {
    GET_RESOURCES,
    GET_RESOURCES_SUCCESS,
    GET_RESOURCES_FAILURE,

    POST_RESOURCE,
    POST_RESOURCE_SUCCESS,
    POST_RESOURCE_FAILURE,

    DELETE_RESOURCE,
    DELETE_RESOURCE_SUCCESS,
    DELETE_RESOURCE_FAILURE,

    SET_SEARCH_TERM
}