const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
const CHANGE_RESPONSIVENESS = 'CHANGE_RESPONSIVENESS';

export {
    TOGGLE_SIDEBAR,
    OPEN_SIDEBAR,
    CHANGE_RESPONSIVENESS
};