const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const EDITOR_STATE_CHANGE = 'EDITOR_STATE_CHANGE';
const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
const CHANGE_RESPONSIVENESS = 'CHANGE_RESPONSIVENESS';

export {
    TOGGLE_SIDEBAR,
    EDITOR_STATE_CHANGE,
    OPEN_SIDEBAR,
    CHANGE_RESPONSIVENESS
};